version: '3.8'
services:
  elasticsearchcortex:
    image: 'elasticsearch:7.11.1'
    container_name: elasticsearchcortex
    restart: unless-stopped
    ports:
      - '0.0.0.0:9600:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch_logs:/usr/share/elasticsearch/logs
    networks:
      - Hive

  cortex:
    image: 'thehiveproject/cortex:3.1.1-1'
    container_name: cortex
    restart: unless-stopped    
    volumes:
      - './cortex/application.conf:/etc/cortex/application.conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${job_directory}:${job_directory}'
    depends_on:
      - elasticsearchcortex
    ports:
      - '0.0.0.0:9001:9001'
    networks:
      - Hive
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./cassandra/data:/var/lib/cassandra/data
    networks:
      - Hive
  ## TheHive
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
      --cortex-keys 9gyI6AKbsOScNP5Hv2IAXGlMSzFGIGua
    networks:
      - Hive
networks:
    Hive:
        driver: bridge
